### ISSUE TITLE
Automate package publish from TravisCI

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#95]
TravisCI can be set up to automatically do an npm publish for tagged builds. Setting this up would be great to reduce the manul steps to get a release out.

**Comment by extr0py** [comment]
For now, all publishes should come from a Linux or OSX box due to #84

**Comment by keforbes** [comment]
Looking [here](https://docs.travis-ci.com/user/deployment/npm/) and [here](https://github.com/bcoe/travis-deploy-example) it looks like all you have to do is add this to the `.travis.yml` file:
```
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
```
And define an `NPM_TOKEN` environment variable in your TravisCI account so your `api_key` isn't publicly visible.

Of course, I haven't tested this since I've never used TravisCI. :smile:
